[package]
name = "enveil"
version = "0.1.0"
edition = "2021"
description = "Secret detection and protection tool"
authors = ["Zat-Code"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
